version: "3.8"
services:
  mqtt:
    image: "eclipse-mosquitto:latest"
    ports:
      - "1883:1883"
    restart: always
  stepper:
    image: "python:3.6"
    # restart: always
  buttons:
    image: "python:3.6"
    # restart: always
  node-red:
    image: "nodered/node-red:latest"
    ports:
      - "1880:1880"
    restart: always
  db:
    image: "hypriot/rpi-mysql:latest"
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: raspberry
  grafana:
    image: "grafana/grafana:latest"
    ports: 
      - "3000:3000"
  website:
    image: "node:latest"
  REST:
    image: "node:latest"
